flyway.url=${DB_URL}
flyway.user=${DB_USERNAME}
flyway.password=${DB_PASSWORD}
flyway.locations=filesystem:src/main/resources/db/migration
flyway.defaultSchema=public
flyway.validateOnMigrate=true
flyway.cleanDisabled=false