flyway.url=jdbc:postgresql://localhost:5435/sportseus_app
flyway.user=semih
flyway.password=SemihSahin111.
flyway.locations=filesystem:src/main/resources/db/migration
flyway.defaultSchema=public
flyway.validateOnMigrate=true
flyway.cleanDisabled=false