spring:
  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST}
      port: ${SPRING_DATA_REDIS_PORT}

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  flyway:
    enabled: true
    default-schema: public
    schemas: public, auth

  jpa:
    hibernate:
      ddl-auto: validate

    show-sql: true

logging:
  level:
    org.hibernate.SQL: DEBUG

auth:
  refresh-cookie:
    name: ${REFRESH_COOKIE_NAME}
    path: ${REFRESH_COOKIE_PATH}
    same-site: ${REFRESH_COOKIE_SAME_SITE}
    secure: ${REFRESH_COOKIE_SECURE}          # prod'da true
    max-age-days: ${REFRESH_COOKIE_MAX_AGE_DAYS}