spring:
  jpa:
    hibernate:
      ddl-auto: validate      # Şemayı Flyway kurar; Hibernate sadece doğrular (drift'i yakalar)
    properties:
      hibernate:
        format_sql: true
    open-in-view: false        # Prod'da da kapalı tutacağız; testte de kapalı olsun

  flyway:
    enabled: true
    schemas: public, auth
    default-schema: public

logging:
  level:
    org.hibernate.SQL: debug
    org.flywaydb: info