[versions]
springBoot = "4.0.5"
flyway = "12.3.0"
postgresql = "42.7.10"

[libraries]
postgresql = { module = "org.postgresql:postgresql", version.ref = "postgresql" }
flyway-core = { module = "org.flywaydb:flyway-core", version.ref = "flyway" }
flyway-database-postgresql = { module = "org.flywaydb:flyway-database-postgresql", version.ref = "flyway" }

[plugins]
spring-boot = { id = "org.springframework.boot", version.ref = "springBoot" }
flyway = { id = "org.flywaydb.flyway", version.ref = "flyway" }